name: win-release
on: 
  push:
    tags:
      - 'v*'
jobs:
  build-win:
    runs-on: windows-2019
    steps:
      - name: Install 7zip
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - uses: actions/checkout@v2
      - uses: bruceadams/get-release@v1.2.2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build
        shell: cmd
        run: call .\build.cmd
      - name: Zip
        shell: cmd
        run: call .\release.cmd
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./jack-win32.zip
          asset_name: jack-win32.zip
          asset_content_type: application/zip
        - uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./jack-win64.zip
            asset_name: jack-win64.zip
            asset_content_type: application/zip

